version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - local-mysql:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomla
      JOOMLA_DB_PASSWORD: joomla

  local-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
